version: '3'
services:
    postgresql:
        image: postgres:13-alpine
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'simplyteam'
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'
        networks:
            sail:
                ipv4_address: 172.21.73.3
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            sail:
                ipv4_address: 172.21.73.4
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            sail:
                ipv4_address: 172.21.0.5
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            sail:
                ipv4_address: 172.21.73.6
    selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            sail:
                ipv4_address: 172.21.73.7

networks:
    sail:
        driver: bridge
        ipam:
            config:
                - subnet: 172.21.0.0/16
volumes:
    sail-postgres:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
