name: Laravel CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: apt get update
        run : sudo apt-get update

      - name: install docker
        run: |
          sudo apt-get install \
            ca-certificates \
            curl \
            gnupg
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx docker-compose

      - name: Install PHP 8.1 and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: create .env secrets
        run: |
          echo ${{ secrets.ENV_FILE }} > .env

      - name: run Laravel sail
        run: docker compose up -d

      - name: Run Laravel Migrations
        run: |
          php artisan migrate --env=.env

      - name: Install Passport
        run: |
          php artisan passport:install --env=.env

      - name: Run Tests
        run: |
          ./vendor/bin/sail test --env=.env
